server:
  port: 8181

#enabling the H2 console
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:innovationCity
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
